.TH "Referência do diretório aux_tools" 3 "Sábado, 3 de Setembro de 2016" "Version 1.0" "MQTT-SNContiki" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório aux_tools \- 
.SH SYNOPSIS
.br
.PP
.SS "Ficheiros"

.in +1c
.ti -1c
.RI "ficheiro \fBbkp_mqtt\&.c\fP"
.br
.ti -1c
.RI "ficheiro \fBold\&.c\fP"
.br
.ti -1c
.RI "ficheiro \fBOLD_2\&.C\fP"
.br
.ti -1c
.RI "ficheiro \fBold_pub_way_qos_maior_0\&.c\fP"
.br
.ti -1c
.RI "ficheiro \fBold_sexta\&.c\fP"
.br
.ti -1c
.RI "ficheiro \fBOLD_SUB\&.C\fP"
.br
.ti -1c
.RI "ficheiro \fBOLD_SUB_2\&.C\fP"
.br
.ti -1c
.RI "ficheiro \fBsabado_list_old\&.c\fP"
.br
.ti -1c
.RI "ficheiro \fBsabado_list_old\&.h\fP"
.br
.RI "\fI
.PP
.nf
    Conjunto de protótipos e definiçoes do protocolo MQTT-SN

.fi
.PP
 \fP"
.ti -1c
.RI "ficheiro \fBserver_udp\&.c\fP"
.br
.in -1c
