.TH "Referência do diretório tools" 3 "Sábado, 3 de Setembro de 2016" "Version 1.0" "MQTT-SNContiki" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório tools \- 
.SH SYNOPSIS
.br
.PP
.SS "Ficheiros"

.in +1c
.ti -1c
.RI "ficheiro \fBsyscalls\&.c\fP"
.br
.RI "\fISystem calls\&. \fP"
.in -1c
