.TH "connect_packet_t" 3 "Domingo, 4 de Setembro de 2016" "Version 1.0" "MQTT-SN_Contiki" \" -*- nroff -*-
.ad l
.nh
.SH NAME
connect_packet_t \- 
.PP
Estrutura de pacotes MQTT-SN do tipo CONNECT\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mqtt_sn\&.h>\fP
.SH "Descrição detalhada"
.PP 
Estrutura de pacotes MQTT-SN do tipo CONNECT\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para MQTT-SN_Contiki a partir do código fonte\&.
