.TH "main_core.c" 3 "Sábado, 3 de Setembro de 2016" "Version 1.0" "MQTT-SNContiki" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main_core.c \- 
Arquivo principal do porte do MQTT-SN, utilizado para testar\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'contiki\&.h'\fP
.br
\fC#include 'lib/random\&.h'\fP
.br
\fC#include 'clock\&.h'\fP
.br
\fC#include 'sys/ctimer\&.h'\fP
.br
\fC#include 'net/ip/uip\&.h'\fP
.br
\fC#include 'net/ipv6/uip-ds6\&.h'\fP
.br
\fC#include 'mqtt_sn\&.h'\fP
.br
\fC#include 'dev/leds\&.h'\fP
.br
\fC#include 'net/rime/rime\&.h'\fP
.br
\fC#include 'simple-udp\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Funções"

.in +1c
.ti -1c
.RI "void \fBmqtt_sn_callback\fP (char *topic, char *message)"
.br
.ti -1c
.RI "void \fBinit_broker\fP (void)"
.br
.ti -1c
.RI "\fBPROCESS\fP (init_system_process,'[Contiki-OS] Iniciando sistema operacional')"
.br
.ti -1c
.RI "\fBPROCESS_THREAD\fP (init_system_process, ev, data)"
.br
.in -1c
.SS "Variáveis"

.in +1c
.ti -1c
.RI "\fBmqtt_sn_con_t\fP \fBmqtt_sn_connection\fP"
.br
.ti -1c
.RI "AUTOSTART_PROCESSES & \fBinit_system_process\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Arquivo principal do porte do MQTT-SN, utilizado para testar\&. 


.PP
\fBAutor:\fP
.RS 4
Ânderson Ignácio da Silva 
.RE
.PP
\fBData:\fP
.RS 4
19 Ago 2016 
.RE
.PP
\fBVeja também:\fP
.RS 4
http://www.aignacio.com 
.RE
.PP

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para MQTT-SNContiki a partir do código fonte\&.
