.TH "md_README" 3 "Sexta, 19 de Agosto de 2016" "Version 1.0" "HomeStark" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README \- README 
#Projeto HomeStark :coffee: 
.PP
 | | | | ___ _ __ ___ ___/ ___|| |_ __ _ _ __| | __ | |_| |/ _ | '_ \fC_ \\ / _ \\___ \\| __/ _\fP | '__| |/ / | _ | (_) | | | | | | __/___) | || (_| | | | < |_| |_|___/|_| |_| |_|___|____/ ____,_|_| |_|_\\
.PP
>make TARGET=srf06-cc26xx
.PP
Desenvolvedor: Ânderson Ignácio da Silva
.PP
Projeto de TCC para criação de uma rede mesh 6LoWPAN utilizando o target cc2650 da Texas Instruments\&. O dispositivo será capaz de se conectar a uma rede mesh 6LoWPAN, comunicando via MQTT-SN com broker remoto e local através de um interface de gestão/configuração\&.
.PP
Características:
.IP "\(bu" 2
[ ] Suporte completo a MQTT-SN
.IP "\(bu" 2
[ ] DTLS sobre UDP
.IP "\(bu" 2
[ ] Informação ao border router sobre o nó
.IP "\(bu" 2
[ ] Comunicação com periféricos e afins
.IP "\(bu" 2
[ ] Documentação em Doxygen
.PP
.PP
Nomenclaturas:
.PP
ETX (expected transmission count) = Medidor de qualidade de caminho entre dois nós em um pacote wireless de rede\&. Basicamente esse núme ro indica o número esperado de transmissões de um pacote necessária s para que não haja erro na recepção no destino\&. 
