.TH "mqtt_queue" 3 "Quinta, 25 de Agosto de 2016" "Version 1.0" "HomeStark" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mqtt_queue \- 
.SH SYNOPSIS
.br
.PP
.SS "Campos de Dados"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "uint8_t \fBmsg_type_q\fP"
.br
.ti -1c
.RI "char * \fBshort_topic\fP"
.br
.RI "\fITipo de mensagem a ser alocada\&. \fP"
.ti -1c
.RI "char * \fBlong_topic\fP"
.br
.ti -1c
.RI "char * \fBmessage\fP"
.br
.in -1c
.in -1c

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para HomeStark a partir do código fonte\&.
