.TH "mqtt_sn_con_t" 3 "Domingo, 4 de Setembro de 2016" "Version 1.0" "MQTT-SN_Contiki" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mqtt_sn_con_t \- 
.PP
Estrutura de conexão ao broker MQTT-SN\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mqtt_sn\&.h>\fP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "struct simple_udp_connection \fBudp_con\fP"
.br
.ti -1c
.RI "uint16_t \fBudp_port\fP"
.br
.RI "\fIPorta UDP de conexão com o broker (default:1884) \fP"
.ti -1c
.RI "uint16_t * \fBipv6_broker\fP"
.br
.RI "\fIEndereço IPv6 do broker UDP\&. \fP"
.ti -1c
.RI "uint8_t \fBkeep_alive\fP"
.br
.RI "\fITempo de requisição Keep Alive para PINGREQ e PINGRESP\&. \fP"
.ti -1c
.RI "const char * \fBclient_id\fP"
.br
.RI "\fIIdentificador de cliente para conexão com o broker MQTT-SN\&. \fP"
.ti -1c
.RI "char * \fBwill_topic\fP"
.br
.ti -1c
.RI "char * \fBwill_message\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Estrutura de conexão ao broker MQTT-SN\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para MQTT-SN_Contiki a partir do código fonte\&.
