.TH "mqtt_sn_connection" 3 "Sábado, 20 de Agosto de 2016" "Version 1.0" "HomeStark" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mqtt_sn_connection \- 
.SH SYNOPSIS
.br
.PP
.SS "Membros públicos"

.in +1c
.ti -1c
.RI "\fBLIST_STRUCT\fP (requests)"
.br
.in -1c
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "struct simple_udp_connection \fBsock\fP"
.br
.ti -1c
.RI "uint16_t \fBnext_message_id\fP"
.br
.ti -1c
.RI "struct ctimer \fBreceive_timer\fP"
.br
.ti -1c
.RI "struct ctimer \fBsend_timer\fP"
.br
.ti -1c
.RI "clock_time_t \fBkeep_alive\fP"
.br
.ti -1c
.RI "\fBconnack_packet_t\fP \fBlast_connack\fP"
.br
.ti -1c
.RI "const char * \fBclient_id\fP"
.br
.ti -1c
.RI "enum mqttsn_connection_status \fBstat\fP"
.br
.ti -1c
.RI "uint8_t \fBconnection_retries\fP"
.br
.ti -1c
.RI "struct process * \fBclient_process\fP"
.br
.ti -1c
.RI "const struct \fBmqtt_sn_callbacks\fP * \fBmc\fP"
.br
.in -1c

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para HomeStark a partir do código fonte\&.
