.TH "MQTT_SN_DEBUG" 3 "Domingo, 4 de Setembro de 2016" "Version 1.0" "MQTT-SN_Contiki" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MQTT_SN_DEBUG \- 
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG_OS\fP"
.br
.RI "\fISe definida habilita mensagens de debug da rede MQTT-SN\&. \fP"
.ti -1c
.RI "#define \fBDEBUG_TASK\fP"
.br
.RI "\fISe definida habilita mensagens de debug de tarefas da fila utilizada pelo MQTT-SN\&. \fP"
.in -1c
.SH "Descrição detalhada"
.PP 
Macros de debug utilizadas para o MQTT-SN 
.SH "Documentação das macros"
.PP 
.SS "#define DEBUG_OS"

.PP
Se definida habilita mensagens de debug da rede MQTT-SN\&. Se definida habilita mensagens de debug do sistema operacional 
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para MQTT-SN_Contiki a partir do código fonte\&.
