.TH "node" 3 "Domingo, 4 de Setembro de 2016" "Version 1.0" "MQTT-SN_Contiki" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node \- 
.PP
Estrutura de fila MQTT-SN\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mqtt_sn\&.h>\fP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "\fBmqtt_sn_task_t\fP \fBdata\fP"
.br
.ti -1c
.RI "struct \fBnode\fP * \fBlink\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Estrutura de fila MQTT-SN\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para MQTT-SN_Contiki a partir do código fonte\&.
