.TH "Pacotes" 3 "Domingo, 4 de Setembro de 2016" "Version 1.0" "MQTT-SN_Contiki" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pacotes \- 
.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "struct \fBdisconnect_packet_t\fP"
.br
.RI "\fIEstrutura de pacote de desconexão do broker MQTT-SN\&. \fP"
.ti -1c
.RI "struct \fBping_req_t\fP"
.br
.RI "\fIEstrutura de pacote de desconexão do broker MQTT-SN\&. \fP"
.ti -1c
.RI "struct \fBpublish_packet_t\fP"
.br
.RI "\fIEstrutura de pacote de publicação MQTT-SN\&. \fP"
.ti -1c
.RI "struct \fBsubscribe_wildcard_packet_t\fP"
.br
.RI "\fIEstrutura de pacote de inscrição do tipo Wildcard MQTT-SN\&. \fP"
.ti -1c
.RI "struct \fBsubscribe_packet_t\fP"
.br
.RI "\fIEstrutura de pacote MQTT-SN do tipo SUBSCRIBE\&. \fP"
.ti -1c
.RI "struct \fBconnect_packet_t\fP"
.br
.RI "\fIEstrutura de pacotes MQTT-SN do tipo CONNECT\&. \fP"
.ti -1c
.RI "struct \fBregister_packet_t\fP"
.br
.RI "\fIEstrutura de pacotes MQTT-SN do tipo REGISTER\&. \fP"
.ti -1c
.RI "struct \fBwilltopic_packet_t\fP"
.br
.RI "\fIEstrutura de pacotes MQTT-SN do tipo WILL TOPIC\&. \fP"
.ti -1c
.RI "struct \fBwillmessage_packet_t\fP"
.br
.RI "\fIEstrutura de pacotes MQTT-SN do tipo WILL MESSAGE\&. \fP"
.ti -1c
.RI "struct \fBregack_packet_t\fP"
.br
.RI "\fIEstrutura de pacotes MQTT-SN do tipo REGACK\&. \fP"
.in -1c
.SS "Funções"

.in +1c
.ti -1c
.RI "struct \fB__attribute__\fP ((packed))"
.br
.in -1c
.SS "Variáveis"

.in +1c
.ti -1c
.RI "\fBdisconnect_packet_t\fP"
.br
.ti -1c
.RI "\fBping_req_t\fP"
.br
.ti -1c
.RI "\fBpublish_packet_t\fP"
.br
.ti -1c
.RI "\fBsubscribe_wildcard_packet_t\fP"
.br
.ti -1c
.RI "\fBsubscribe_packet_t\fP"
.br
.ti -1c
.RI "\fBconnect_packet_t\fP"
.br
.ti -1c
.RI "\fBregister_packet_t\fP"
.br
.ti -1c
.RI "\fBwilltopic_packet_t\fP"
.br
.ti -1c
.RI "\fBwillmessage_packet_t\fP"
.br
.ti -1c
.RI "\fBregack_packet_t\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Macros de debug utilizadas para o MQTT-SN 
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para MQTT-SN_Contiki a partir do código fonte\&.
