.TH "puback_packet_t" 3 "Sábado, 20 de Agosto de 2016" "Version 1.0" "HomeStark" \" -*- nroff -*-
.ad l
.nh
.SH NAME
puback_packet_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "uint8_t \fBlength\fP"
.br
.ti -1c
.RI "uint8_t \fBtype\fP"
.br
.ti -1c
.RI "uint16_t \fBtopic_id\fP"
.br
.ti -1c
.RI "uint16_t \fBmessage_id\fP"
.br
.ti -1c
.RI "uint8_t \fBreturn_code\fP"
.br
.in -1c

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para HomeStark a partir do código fonte\&.
