.TH "regack_packet_t" 3 "Sábado, 3 de Setembro de 2016" "Version 1.0" "MQTT-SNContiki" \" -*- nroff -*-
.ad l
.nh
.SH NAME
regack_packet_t \- 
.PP
Estrutura de pacotes MQTT-SN do tipo REGACK\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mqtt_sn\&.h>\fP
.SH "Descrição detalhada"
.PP 
Estrutura de pacotes MQTT-SN do tipo REGACK\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para MQTT-SNContiki a partir do código fonte\&.
