.TH "short_topics_t" 3 "Domingo, 4 de Setembro de 2016" "Version 1.0" "MQTT-SN_Contiki" \" -*- nroff -*-
.ad l
.nh
.SH NAME
short_topics_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "char * \fBtopic_name\fP"
.br
.ti -1c
.RI "uint8_t \fBshort_topic_id\fP"
.br
.ti -1c
.RI "uint8_t \fBsubscribed\fP"
.br
.in -1c

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para MQTT-SN_Contiki a partir do código fonte\&.
