.TH "subscribe_wildcard_packet_t" 3 "Sábado, 3 de Setembro de 2016" "Version 1.0" "MQTT-SNContiki" \" -*- nroff -*-
.ad l
.nh
.SH NAME
subscribe_wildcard_packet_t \- 
.PP
Estrutura de pacote de inscrição do tipo Wildcard MQTT-SN\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mqtt_sn\&.h>\fP
.SH "Descrição detalhada"
.PP 
Estrutura de pacote de inscrição do tipo Wildcard MQTT-SN\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para MQTT-SNContiki a partir do código fonte\&.
