.TH "tools/syscalls.c" 3 "Sábado, 3 de Setembro de 2016" "Version 1.0" "MQTT-SNContiki" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tools/syscalls.c \- 
.PP
System calls\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sys/types\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP   0"
.br
.ti -1c
.RI "#define \fBPRINTF\fP(\&.\&.\&.)"
.br
.in -1c
.SS "Funções"

.in +1c
.ti -1c
.RI "caddr_t \fB_sbrk\fP (int incr)"
.br
.RI "\fIEnlarges the allocated heap space\&. \fP"
.in -1c
.SH "Descrição detalhada"
.PP 
System calls\&. 


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para MQTT-SNContiki a partir do código fonte\&.
