.TH "todo" 3 "Domingo, 4 de Setembro de 2016" "Version 1.0" "MQTT-SN_Contiki" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Lista de tarefas 

.IP "\fBGlobal \fBmqtt_sn_check_rc\fP (uint8_t rc)\fP" 1c
Expandir o tipo de falha para tornar mais precisa a depuração futura  
.IP "\fBGlobal \fBmqtt_sn_delete_queue\fP ()\fP" 1c
Adicionar opção de exclusão intermediária  
.IP "\fBGlobal \fBmqtt_sn_delete_queue\fP ()\fP" 1c
Adicionar opção de exclusão intermediária  
.IP "\fBGlobal \fBmqtt_sn_insert_queue\fP (\fBmqtt_sn_task_t\fP new)\fP" 1c
Melhorar alocação dinâmica de memória  
.IP "\fBGlobal \fBmqtt_sn_recv_parser\fP (const uint8_t *data)\fP" 1c
Rever o short topic para adequar bytes [2][3] juntos\&.\&. 
.PP
Rever o short topic para adequar bytes [2][3] juntos\&.\&.\&.  
.IP "\fBGlobal \fBSUCCESS_CON\fP \fP" 1c
Implementar mais tipos de erros 
.PP

