.TH "topic_map" 3 "Sábado, 20 de Agosto de 2016" "Version 1.0" "HomeStark" \" -*- nroff -*-
.ad l
.nh
.SH NAME
topic_map \- 
.SH SYNOPSIS
.br
.PP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "uint16_t \fBtopic_id\fP"
.br
.ti -1c
.RI "char \fBtopic_name\fP [MQTT_SN_MAX_TOPIC_LENGTH]"
.br
.ti -1c
.RI "struct \fBtopic_map\fP * \fBnext\fP"
.br
.in -1c

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para HomeStark a partir do código fonte\&.
